// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLqiBfQVbPY9lpzv-Cw_rIJKvxablaS24',
    appId: '1:994074691087:web:34749c616fb68de0a3c57a',
    messagingSenderId: '994074691087',
    projectId: 'signin-app-9d55f',
    authDomain: 'signin-app-9d55f.firebaseapp.com',
    storageBucket: 'signin-app-9d55f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMAI2kgSR9zmuqIaY_swNiRUkFsVJ1PSQ',
    appId: '1:994074691087:android:b101ffe26719bfe1a3c57a',
    messagingSenderId: '994074691087',
    projectId: 'signin-app-9d55f',
    storageBucket: 'signin-app-9d55f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdAVKpm1NZ7E8BhUpj-VMUmvN1A2_FwqI',
    appId: '1:994074691087:ios:318392e6779fd351a3c57a',
    messagingSenderId: '994074691087',
    projectId: 'signin-app-9d55f',
    storageBucket: 'signin-app-9d55f.firebasestorage.app',
    iosBundleId: 'com.example.loginSignupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdAVKpm1NZ7E8BhUpj-VMUmvN1A2_FwqI',
    appId: '1:994074691087:ios:318392e6779fd351a3c57a',
    messagingSenderId: '994074691087',
    projectId: 'signin-app-9d55f',
    storageBucket: 'signin-app-9d55f.firebasestorage.app',
    iosBundleId: 'com.example.loginSignupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLqiBfQVbPY9lpzv-Cw_rIJKvxablaS24',
    appId: '1:994074691087:web:68964ea7bfcb1711a3c57a',
    messagingSenderId: '994074691087',
    projectId: 'signin-app-9d55f',
    authDomain: 'signin-app-9d55f.firebaseapp.com',
    storageBucket: 'signin-app-9d55f.firebasestorage.app',
  );
}
